version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "${RCON_PASSWORD}"
    volumes:
      - ./minecraft-server/data:/data
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      RCON_PASSWORD: "${RCON_PASSWORD}"
    depends_on:
      - minecraft
    restart: unless-stopped