version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      ONLINE_MODE: "false"
    volumes:
      - ./minecraft-server/data:/data
    healthcheck:
      test: ["CMD", "mc-status", "localhost:25565"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      RCON_PASSWORD: "${RCON_PASSWORD}"
    depends_on:
      minecraft-server:
        condition: service_healthy
    restart: unless-stopped